task: class_uncertain
planner: random_policy
global_seed: 0
vis: false
vis_graph: false
print_options: a,ab,r,abp
max_steps: 10
batch_size: 10
num_skeletons: 10
flat_sample: false
flat_width: 1
pwa: 0.2
pwk: 3.0
envelope_threshold: 1
num_samples: 100
gamma: 0.95
planner: tampura_policy
decision_strategy: prob
learning_strategy: bayes_optimistic
load: null
real_camera: False
real_execute: False
symk_selection: unordered
symk_direction: fw
symk_simple: true
from_scratch: true